################################################################################################
# Creating a SQL Service Instance in Microsoft Azure                                            #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2019                                                    #
#                                                                                              #
# NOTE: just set the location, Resoruce Group, Storage Account, Virtual Network, Public IP,    #
# Security Group and more variables as you wish!                                               #
#                                                                                              #
# IMPORTANT: for further information about Microsoft Azure, please take a look at this link:   #
# https://docs.microsoft.com/en-us/azure/                                                      #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Create SQL Service Instance in Microsoft Azure
  hosts: all
  connection: local
  tasks:
  - name: Create (or update) SQL Server
    azure_rm_sqlserver:
      resource_group: "{{ resourcegroup }}"
      name: "{{ server_name }}"
      location: "{{ location }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      
  - name: Sending E-mail to Users
    hosts: localhost
    gather_facts: False
    connection: local
    tasks:
    - name: Send email to user with SQL Service information
      sendgrid:
        api_key: "{{ sendgrid_api_key }}"
        subject: "{{ sendgrid_subject }}"
        body: "{{ sendgrid_body }}"
        to_addresses: "{{ user_email }}"
        html_body: yes
        from_address: "{{ sendgrid_from_address }}"
