- name: Delete a Complete Resource Group in Azure
  hosts: all
  connection: local
  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: "{{ resourcegroup }}"
        location: "{{ location }}"
        state: absent
        force: yes
