################################################################################################
# Deleting an Entire Environment in Microsoft Azure                                            #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2016                                                    #
#                                                                                              #
# NOTE: just set the location, Resoruce Group, Storage Account, Virtual Network, Public IP,    #
# Security Group and more variables as you wish!                                               #
#                                                                                              #
# IMPORTANT: for further information about Microsoft Azure, please take a look at this link:   #
# https://docs.microsoft.com/en-us/azure/                                                      #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
################################################################################################
# Deleting an Entire Environment in Microsoft Azure                                            #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2016                                                    #
#                                                                                              #
# NOTE: just set the location, Resoruce Group, Storage Account, Virtual Network, Public IP,    #
# Security Group and more variables as you wish!                                               #
#                                                                                              #
# IMPORTANT: for further information about Microsoft Azure, please take a look at this link:   #
# https://docs.microsoft.com/en-us/azure/                                                      #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################

- name: Delete an entire Environment in Azure
  hosts: localhost
  gather_facts: false
  connection: local

  # Getting facts!
  tasks:
    - name: Get resource groups by tags
      azure_rm_resourcegroup_facts:
        tags: "{{ mytags }}"
              #tags:
              #- family:ansibletest76163
      register: taggedresources 

    - name: Get VMs by tags
      azure_rm_virtualmachine_facts:
        tags: "{{ mytags }}"
      register: taggedvms

    - name: Get virtual network by tags
      azure_rm_virtualnetwork_facts:
        tags: "{{ mytags }}"
      register: taggedvirtualnetwork
           
- hosts: localhost  
  vars: 
    resourcegroup: "{{ taggedresources.resourcegroups[0].name }}"
    vmname: "{{ taggedvms.vms[0].name }}"
    storageaccount: "{{ taggedvms.vms[0].storage_account_name }}"
    storageblob: "{{ taggedvms.vms[0].storage_blob_name }}"
    nicname: "{{ taggedvms.vms[0].network_interface_names[0] }}"

  tasks: 
    - name: Debug tagged resources
      debug:
        verbosity: 2
        var: taggedvms
        #msg: 
        # - "taggedsa: {{ storageaccount }}"
        #  - "resourcegroup name (from var): {{ resourcegroup }}"
        
    - name: Delete virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: "{{ vmname }}"
        state: absent
        remove_on_absent:
          - network_interfaces
          - virtual_storage
#
#    - name: Delete public ip
#      azure_rm_publicipaddress:
#        resource_group: "{{ resourcegroup }}"
#        name: "{{ publicip }}"
#        state: absent
#
#    - name: Delete subnet
#      azure_rm_subnet:
#        resource_group: "{{ resourcegroup }}"
#        name: "{{ subnet }}"
#        address_prefix: "{{ subnet_prefix }}"
#        virtual_network: "{{ virtualnetwork }}"
#        state: absent
#
#    - name: Delete virtual network
#      azure_rm_virtualnetwork:
#        resource_group: "{{ resourcegroup }}"
#        name: "{{ virtualnetwork }}"
#        address_prefixes: "{{ address_prefix }}"
#        state: absent
#
#    - name: Delete security group
#      azure_rm_securitygroup:
#        resource_group: "{{ resourcegroup }}"
#        name: "{{ secgroup }}"
#        state: absent
#
#    - name: Delete storage account
#      azure_rm_storageaccount:
#        resource_group: "{{ resourcegroup }}"
#        name: "{{ storageaccount }}"
#        state: absent
#        account_type: Standard_LRS
#
#    - name: Delete a resource group
#      azure_rm_resourcegroup:
#        name: "{{ resourcegroup }}"
#        location: "{{ location }}"
#        state: absent
