
- name: Delete a Virtual Machine in Azure
  hosts: all
  connection: local
  tasks:
  
    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: "{{ vmname }}"
        state: absent
